version: 3.5
services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
  app:
    image: node:latest
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - NEXT_PUBLIC_BASE_URL: http://todo.at
    ports:
      - "3000:3000"
